config/routes.rb
CodeTweet::Application.routes.draw do

  devise_for :users
  resources :dashboards, only: [:show]
  root 'tweets#index'
  resources :tweets
  

end

app/models/codebuddy.rb
class Codebuddy < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

  def find_user_byID
    User.find_by_id self.user_id 
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.order(created_at: :desc)
  end

  def new
    @tweet = Tweet.new
  end

  def create 
    if current_user
      @tweet = Tweet.create(tweet_params)
      @tweet.user_id = current_user.id
      @tweet.save
    else
      flash[:not_logged_in] = "Not logged in"
    end
    redirect_to :root
  end

  private

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/dashboards/show.html.erb
<h2>Welcome to your User Dashboard <%= @user.email %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeTweet</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default background-nav">
    <div class="container-fluid">
      <div class="row ">
        <div class="row navbar-brand col-sm-4 text-center">
          <li><%= link_to 'New Tweet </>', new_tweet_path %></li>
        </div>
        <div class="text-center col-sm-4">
          <%= link_to "Code-tweet", root_path,class:"logo" %>
        </div>
        <ul class="col-sm-4 nav navbar-nav navbar-right">
          <div class="row">
            <div id="nav-links" class="col-sm-4 col-sm-offset-6 margin-top">
              <% if user_signed_in? %>
                <li><%= link_to 'My Dashboard', dashboard_path(current_user) %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
                <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <% end %>
            </div>
          </div>
        </ul>
    </div><!-- /.container-fluid -->
  </nav>
  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/tweets/_tweet.html.erb
<div class = "form_style">
  <br /><br />
  <h3><%= tweet.message %></h3><br />
  <%= tweet.find_user_byID.email %><br />
  <%= tweet.created_at %>
</div>
<br/>

app/views/tweets/index.html.erb
<h2 class = "text-center">Latest news from the 127.0.0.1:</h2>


<div class= "col-xs-4 col-xs-offset-4 text-center">
  <%= render @tweets %>
</div>

app/views/tweets/new.html.erb
<div class = "form_style col-xs-4 col-xs-offset-4"
  <h2>Add a Tweet</h2>

  <%= simple_form_for(@tweet) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :message, required: true, autofocus: true %>
    </div>
    <br/>
    <div class="form-actions">
      <%= f.button :submit, "Code-tweet", class:'btn btn-primary' %>
    </div>
  <% end %>
</div>